### ISSUE TITLE
Single Line Comment in Language Block Codes are hidden

### ISSUE THREAD

**Issue by ebouchut** [HeroBlackInk/ultimate-todoist-sync-for-obsidian#69]
👏 First off thank you @HeroBlackInk for this useful plugin.

I noticed the following issue.

## Summary

When editing a note with a **single-line comments in a language code block, with `Ultimate Todoist Sync for Obsidian` plugin enabled, then the comment is hot shown (whatever the value of `Editing Mode` (`Live Preview` or `Source mode`)).

## Description of the Issue

When I type this in an Obsidian note:
````
```java
// Single-line comment
```
````

Then I **expect**, the `// Single-line comment` to be shown in the editor, like so

```java
// Single-line comment
```

❌ Whereas it is not when `Ultimate Todoist Sync for Obsidian` is **enabled** whatever the value of `Editing Mode` (`Live Preview` or `Source mode`).

FYI, the issue is the same for a single-line comment in a Ruby code block.
````
```ruby
# Single-line comment
```
````

✅ When I disable the `Ultimate Todoist Sync for Obsidian` plugin, the comment is shown as expected.

## How to Reproduce this Issue?

- create a new Obsidian Vault
- Install and enable the `Ultimate Todoist Sync for Obsidian` plugin
- Create a new note and paste this
  ````
  ```java
  // Single-line comment
  ```
  ````

**Comment by MAWSpitau** [comment]
I do have the same problem, but with HTML-comments like:

`<!-- Kommentar -->`

![This is what the hidden line looks like... ](https://github.com/HeroBlackInk/ultimate-todoist-sync-for-obsidian/assets/539371/b2803bde-59a7-4c19-8fc8-39618ef6265c)

I would love to have this Bug fixed and see my comments again ;)

**Comment by MAWSpitau** [comment]
You can fix this with this workaround:

- go to the styles.css of the plugin. (vault/.obsidian/plugins/ultimate-todoist-sync)

Change this:
`
.cm-line:not(:hover):not(.cm-active) span.cm-comment {
    display: none;
}
`
to this:
`/*
.cm-line:not(:hover):not(.cm-active) span.cm-comment {
    display: none;
}
*/
`

# What it does:

- The ID of the Todoist task is written down in %% %% Obsidians Comment syntax. 
- The author does not want to see us the id, so he hides it.
- But ALL Comments are now hidden. 
- The change above is commenting this feature out. 
- Now you can see all your comments again. Even the ones in the todoist-Line, but that does not bother me.

**Comment by ebouchut** [comment]
Thank you @MAWSpitau I will use this tip.

**Comment by ebouchut** [comment]
🧐 I will try to build a CSS selector to only target/hide the Todoist comments.

**Comment by ebouchut** [comment]
I have a CSS rule handy to hide the _start_ and _end_ Obsidian comment surrounding the `todoist_id`.

```css
.cm-line:not(:hover):not(.cm-active) > .cm-comment.cm-comment-start:has(~ .dataview.inline-field > .dataview.inline-field-key[data-dv-key="todoist_id"]),
.cm-line:not(:hover):not(.cm-active) > .cm-comment.cm-comment-start:has(~ .dataview.inline-field > .dataview.inline-field-key[data-dv-key="todoist_id"]) ~ .cm-comment.cm-comment-end
{
    display: none;
}
```

✅ This fixed the issue for me, it:
- hides the `todoist_id` _start_ and _end_ comment delimiters (`%%`) except when we hover over the line or edit the task. 
- 🎉 does not hide other types of comments (I tested Java HTML and Ruby)

It is brittle because it depends on the CSS classes of the [Tasks Obsidian plugin](https://github.com/obsidian-tasks-group/obsidian-tasks).

@MAWSpitau and anyone interested Let me know if this also fixes the issue for you.
